### ISSUE TITLE
Kernel build error

### ISSUE THREAD

**Issue by DawyD** [Sampas/bm3dcl#1]
Hi, I wanted to run your algorithm but I was not able to get it working. It seems that there is something wrong with the kernel. 

```
Starting kernel build with options:  -cl-nv-verbose -cl-std=CL1.1 -DWIDTH=256 -DHEIGHT=256 -DUSE_PLATFORM=0 -DSIGMA=25
OpenCL error code -11 at /mnt/home/honzatko/BM3DCL/main.cpp [176]: clBuildProgram(program, 0, NULL, options.c_str(), NULL, NULL)
```

platform: NVIDIA CUDA; device: GeForce GTX 980; 
OS: linux; CUDA toolkit 7.5;  driver version 367.27

**Comment by Sampas** [comment]
Hi, does it find and select the platform successfully? Can you check the build log by removing the CL_CHECK from the clBuildProgram so that it won't exit before printing out the build log? That should be modified so that the log is always printed if the build fails...

**Comment by DawyD** [comment]
Thank you. The only problem was, that cmake did not copy header files for the kernel to the "build" directory I made. (I used following commands: mkdir build; cd build; cmake ..; make) I copied them manually and everything works now.

**Comment by Sampas** [comment]
Nice, good that you got it solved. Yeah, those files should be copied also in the cmake file, I'll add them.
